name: CI

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4.2.1
      - name: Autenticação docker hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Build e push da imagem docker
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            caiovrodrigues/sistema-bancario-com-threads:v1
            caiovrodrigues/sistema-bancario-com-threads:latest
    
